# Generated by Django 5.2.4 on 2025-08-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='meeting_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
